<?php

namespace App\Services;

use App\Models\Payment;
use App\Models\User;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;

/**
 * Persists and validates payment proof uploads (Phase 2B).
 *
 * Rules (PRD §23.7): allowed MIME = JPG/JPEG/PNG/PDF; max size 5 MB; file name
 * is generated by the system (UUID); the original file name is never stored as
 * the path. Files live under `storage/app/payments` (NOT public) and are only
 * served through a controller (plan §5.10). A PaymentProof row is immutable
 * (PRD §16.6): re-upload creates a new row, never overwrites.
 */
class PaymentProofService
{
    /** Allowed extensions + their MIME types (PRD §23.7). */
    protected const ALLOWED = [
        'jpg' => 'image/jpeg',
        'jpeg' => 'image/jpeg',
        'png' => 'image/png',
        'pdf' => 'application/pdf',
    ];

    /** Max upload size in bytes (5 MB, PRD §23.7). */
    protected const MAX_SIZE = 5 * 1024 * 1024;

    protected const DISK = 'local';
    protected const DIR = 'payments';

    /**
     * Validate and persist an uploaded payment proof.
     *
     * @throws \Illuminate\Validation\ValidationException
     * @return \App\Models\PaymentProof
     */
    public function store(Payment $payment, UploadedFile $file, ?User $uploader = null)
    {
        $this->validate($file);

        $ext = strtolower($file->getClientOriginalExtension());
        $uuid = (string) Str::uuid();
        $storedName = $uuid . '.' . $ext;

        $path = Storage::disk(self::DISK)->putFileAs(self::DIR, $file, $storedName);
        if ($path === false) {
            throw ValidationException::withMessages([
                'payment_proof' => ['Gagal menyimpan bukti pembayaran. Mohon coba lagi.'],
            ]);
        }

        return $payment->proofs()->create([
            'uuid' => $uuid,
            'id_payment' => $payment->id,
            'file_path' => $path,
            'original_name' => $file->getClientOriginalName(),
            'mime_type' => $file->getMimeType(),
            'file_size' => $file->getSize(),
            'uploaded_by' => $uploader?->id,
        ]);
    }

    /**
     * Validate MIME type, extension and size. Returns void; throws otherwise.
     *
     * @throws \Illuminate\Validation\ValidationException
     */
    public function validateValid(UploadedFile $file): void
    {
        $this->validate($file);
    }

    /**
     * Validate MIME type, extension and size. Returns void; throws otherwise.
     *
     * @throws \Illuminate\Validation\ValidationException
     */
    protected function validate(UploadedFile $file): void
    {
        $ext = strtolower($file->getClientOriginalExtension());

        if (!array_key_exists($ext, self::ALLOWED)) {
            throw ValidationException::withMessages([
                'payment_proof' => ['Format file tidak diizinkan. Gunakan JPG, JPEG, PNG, atau PDF.'],
            ]);
        }

        $mime = strtolower((string) $file->getMimeType());
        if ($mime !== self::ALLOWED[$ext]) {
            throw ValidationException::withMessages([
                'payment_proof' => ['MIME type file tidak sesuai dengan ekstensinya.'],
            ]);
        }

        if ($file->getSize() > self::MAX_SIZE) {
            throw ValidationException::withMessages([
                'payment_proof' => ['Ukuran file melebihi batas maksimum 5 MB.'],
            ]);
        }
    }
}